import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/components/providers";
import { cookies } from "next/headers";
import { getCurrentUser } from "@/lib/api/auth";
import { ThemeProvider } from "@/lib/theme/theme-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const user = await getCurrentUser(cookieStore.toString());
  const isDark = (user as any)?.themeMode === 'DARK';

  return (
    <html
      lang="en"
      className={isDark ? 'dark' : undefined}
      data-color={(user as any)?.colorMode?.toLowerCase() ?? 'black'}
    >
      <body>
        <Providers>
          <ThemeProvider
            initialThemeMode={(user as any)?.themeMode ?? 'LIGHT'}
            initialColorMode={(user as any)?.colorMode ?? 'BLACK'}
          >
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
